### ISSUE TITLE
Cross-Origin Request Blocked:

### ISSUE THREAD

**Issue by elhananjair** [tncrazvan/sveltekit-sse#11] opened 2023-10-25 16:38 UTC
Hello @tncrazvan 
After the update I am getting this error on firefox:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by elhananjair** [comment] 2023-10-25 17:28
It seems it works with other paths like `/localhost` based on the way I am using the package and your demo [here](https://github.com/tncrazvan/sveltekit-sse-issue-10)

**Comment by tncrazvan** [comment] 2023-10-25 21:16
Hi @elhananjair ,
The [project you mentioned](https://github.com/tncrazvan/sveltekit-sse-issue-10) works just fine for me on firefox.

![Peek 2023-10-25 22-51](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/add9641a-73d9-452e-9dc9-4a6205b8bce4)

The errors you see are standard behaviour for some browsers due to page reloading (you're essentially closing the sse stream without notice when you close a tab).

I tested this on firefox version `Mozilla Firefox 118.0.2`.


Your issue seems to be related http headers.

Your configuration is either missing some required headers for your setup or your disallowing some origins in your http response.

The `event` itself allows you to set specific http headers, so you could do something like this

```js
/** src/lib/server/longrunningtask.js */

import { event } from 'sveltekit-sse'

export function long_running_task() {
  return event(async emit => {
    //...
    emit('some data...')
    //...
  })
  .setHeader("Access-Control-Allow-Origin", "*")
  .toResponse()
}
```

You probably shouldn't allow `*` in a production environment though.

There's not much else I can help you with unless you reproduce the error in a repository where I can debug the project.

**Comment by elhananjair** [comment] 2023-10-26 10:26
Yeah with `.setHeader("Access-Control-Allow-Origin", "*")` it works fine.

**Closed** 2023-10-26 10:41 UTC
